gnl scanner
awnzl/gnl_go pull request #1
Opened 2021-04-29 10:40 UTC by awnzl

2021-04-30 06:36 UTC, sladonia requested changes

2021-04-30 06:36 UTC, sladonia commented on Makefile
> +GOBASE	:= $(shell pwd)
можно использовать относительный путь, чтобы без pwd

2021-04-30 06:36 UTC, sladonia commented on pkg/gnl/gnl_test.go
> +func TestGetNextLine(t *testing.T) {
Тест должен быть написан в таком формате, тобы из него было понятно как мы хотим использовать функцию.

Мы реализуем паттерн генератор. Самый первый пример из статьи: https://blog.golang.org/pipelines#TOC_3.

Мы хотим в цикле вычитывать все что вернется из канала, пока тот не закроется

пример использования
```
func genInts() <-chan int {
	intCh := make(chan int)

	go func() {
		defer close(intCh)

		intCh <- 5
	}()

	return intCh
}

func main() {
	intCh := genInts()

	for intVal := range intCh {
		fmt.Println("val:", intVal)
	}
}
```

2021-04-30 06:36 UTC, sladonia commented on pkg/gnl/gnl_test.go
> +	canceled := GetNextLine(ctx, strings.NewReader("first string\nsecond string"))
должен быть отдельный тест на отмену. ты же передаешь здесь уже отмененный контекст. это не то поведение которое ты хочешь протеситровать. ты хочешь проверить что можно вычитать 1 или 2 значения, отменить контекст и убедиться что функция правильно завершается

2021-04-30 06:36 UTC, sladonia commented on pkg/gnl/gnl_test.go
> +	for i := 0; i < len(wants); i++ {
то же замечание что и для предыдущего теста. В тесте мы показываем как правильно пользоваться функцией. Здесь мы тоже хотим вычитывать из канала в цикле пока один из каналов не закроется или errCh не вернет ошибку

пример
```
Loop:
	for {
		select {
		case err, ok := <-errCh:
			if !ok {
				break Loop
			}

			fmt.Println(err)

			break Loop
		case b, ok := <-bytesCh:
			if !ok {
				break Loop
			}

			fmt.Println(b)
		}
	}
```

2021-04-30 06:36 UTC, sladonia commented on pkg/gnl/gnl_test.go
> +	canceled, errc := GetNextLineErr(ctx, strings.NewReader("first string"))
тоже отдельный тест на отмену контекста

2021-04-30 06:36 UTC, sladonia commented on pkg/gnl/gnl.go
> +	errc := make(chan error, 1)
здесь должен быть небуферизированный канал. Если я здесь сделаю небуферезированный канал и запущу тесты - будет дед лок. Но это потому что тесты написаны неправильно

2021-04-30 06:36 UTC, sladonia commented on pkg/gnl/gnl.go
> +			close(errc)
`errc` - должен закрыватся точно так же как и `out` - один раз в defer

2021-04-30 06:36 UTC, sladonia commented on pkg/gnl/gnl.go
> +	}
после цикла должна проверятся ошибка `scanner.Err()` - если ошибка не nil - ее нужно писать в канал ошибок. Так как реализовано сейчас - в канал ошибок вообще ничего не пишется

2021-05-05 16:46 UTC, sladonia commented on gnl_test.go
> +	ctx, _ := context.WithCancel(context.Background())
если cancel здесь не используешь, то пиши просто `ctx := context.Background()`

2021-05-05 16:46 UTC, sladonia commented on gnl_test.go
> +	wants := [][]byte{
want

2021-05-05 16:46 UTC, sladonia commented on gnl_test.go
> +	for v := range ch {
так ок. просто возможный вариант
```
	i := 0

	for line := range ch {
		assert.Equal(t, want[i], line)
		i++
	}

	assert.Equal(t, len(want), i)
```

2021-05-05 16:46 UTC, sladonia commented on gnl_test.go
> +	v, isOpened := <-ch
isOpen

2021-05-05 16:46 UTC, sladonia commented on gnl_test.go
> +	assert.Equal(t, errors.New("context canceled"), ctx.Err())
для сравнения новые ошибки не создаем. используем:
`assert.EqualError(t, ctx.Err(), "context canceled")`
или еще точнее было бы:
`assert.EqualError(t, ctx.Err(), context.Canceled.Error())`

 Ошибки ведь значения, та что ты создаешь будет не то же самое значение что тебе возвращают. Здесь просто так совпало что библиотека assert, наверное, под какпотом для `assert.Equal()` когда сравниваешь ошибки, их текстово сравнивает. а если бы ты например сравнивал так
```
	if ctx.Err() != errors.New("context canceled") {
		t.Fail()
	}
```
тест бы не прошел

в других местах тоже поправь

2021-05-05 16:46 UTC, sladonia commented on gnl.go
> +		for {
ошибку сканера неправильно хендлишь. из документации сканера:
```
It returns false when the
// scan stops, either by reaching the end of the input or an error.
// After Scan returns false, the Err method will return any error that
// occurred during scanning, except that if it was io.EOF, Err
// will return nil.
```

правильно будет так:
```
		for {
			if !scanner.Scan() {
				if scanner.Err() != nil {
					errc <- scanner.Err()
				}

				return
			}

			select {
			case <-ctx.Done():
				errc <- ctx.Err()
				return
			case out <- scanner.Bytes():
			}
		}
```

2021-05-05 18:24 UTC, awnzl commented on gnl_test.go
> +	for v := range ch {
показалось, что так нагляднее будет

2021-05-06 07:49 UTC, sladonia approved these changes

2021-06-11 11:27 UTC, merged